### ISSUE TITLE
prod 500 errors for /v1/profile on possible network glitch

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#151]
This may have just been a network glitch but there was a burst of 500's in production, about 24. But this code could use a null check. - https://github.com/mozilla/fxa-profile-server/blob/master/lib/server/web.js#L64

```
{"Timestamp":1443753325303000000,"Logger":"fxa-profile-server","Type":"server.summary","Severity":2,"Pid":2069,"EnvVersion":"2.0",
 "Fields":{"code":500,"method":"get","errno":999,"path":"/v1/profile",
  "agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0","t":22156,
  "stack":"TypeError: Uncaught error: Cannot read property 'code' of undefined
    at Request._callback (/data/fxa-profile-server/lib/server/web.js:64:19)
    at Request.self.callback (/data/fxa-profile-server/node_modules/request/request.js:372:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/data/fxa-profile-server/node_modules/request/request.js:1310:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/data/fxa-profile-server/node_modules/request/request.js:1258:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:492:13)"}}
```

**Comment by seanmonstar** [comment]
We can add a null check for sure. I think this would still be a 503,
however.

**Comment by jrgm** [comment]
> We can add a null check for sure. I think this would still be a 503, however.

Yeah, valid point; it is either 500 or 503, probably 503. Such a limited set of choices. Still, marginally better to have a diagnosed error (possibly still including a stack), than a TypeError.

**Comment by jrgm** [comment]
>  Such a limited set of choices.

Or, invent '530 Remote dependent service failed' or perhaps ' 503 SOA FTW' ;-)
