### ISSUE TITLE
limits code is resulting in only the '_large' variant being stored in s3

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#167]
re: https://github.com/mozilla/fxa-profile-server/pull/157/files#diff-e1b05bbd72783375d7e1f2df53824f9fR25

In stage with train-49, only the '_large' variant is being stored in s3.

**Comment by vladikoff** [comment]
Log from latest:

```
[ec2-user@ip-172-31-36-37 ~]$ tail -f /var/log/fxa-profile-worker.log 
fxa-profile-server.compute.image-cc.INFO: time.ms.gm.large 262
fxa-profile-server.compute.image-cc.DEBUG: process.end {"bytes":2473,"variant":"large"}
fxa-profile-server.img.VERBOSE: proxied {"method":"upload","args":3}
fxa-profile-server.img.local.DEBUG: upload.start c19053325d30ca72eb8f62152d575d91_large
fxa-profile-server.img.local.DEBUG: upload.end c19053325d30ca72eb8f62152d575d91_large
fxa-profile-server.compute.image-cc.INFO: time.ms.s3.large 13
fxa-profile-server.compute.DEBUG: image-cc process 6315 completed work in 0.28s
fxa-profile-server.bin.worker.INFO: listening http://127.0.0.1:1113
fxa-profile-server.bin.worker.INFO: listening http://127.0.0.1:1113
fxa-profile-server.bin.worker.INFO: listening http://127.0.0.1:1113
fxa-profile-server.server.worker.DEBUG: worker.receive {"contentLength":55305}
fxa-profile-server.compute.INFO: image-cc spawned new worker process (19026) 1/5 processes running
fxa-profile-server.compute.DEBUG: image-cc passing compute job to process 19026
fxa-profile-server.compute.INFO: image-cc spawned new worker process (19028) 2/5 processes running
fxa-profile-server.compute.DEBUG: image-cc passing compute job to process 19028
fxa-profile-server.compute.INFO: image-cc spawned new worker process (19030) 3/5 processes running
fxa-profile-server.compute.DEBUG: image-cc passing compute job to process 19030
fxa-profile-server.compute.image-cc.INFO: worker.config {"config":{"driver":"local","providers":{"gravatar":"^http(://www|s://secure)\\.gravatar\\.com/avatar/[0-9a-f]{32}(\\?s=\\d+)?$","fxa":"^https://latest.dev.lcip.org/profile/a/[0-9a-f]{32}$"},"uploads":{"dest":{"public":"/data/fxa-profile-server/var/public"},"maxSize":1048576},"compute":{"maxBacklog":500,"maxRequestTime":10,"maxProcesses":5},"gm":{"limits":{"disk":"2MB","files":"8","map":"2MB","memory":"1MB","pixels":"16K","threads":"8"}},"url":"https://latest.dev.lcip.org/profile/a/{id}"}}
fxa-profile-server.compute.image-cc.DEBUG: onMessage 3649226ad8bf6b4e898a9cf97c62ca3a
fxa-profile-server.compute.image-cc.DEBUG: process.start {"bytes":55305,"variant":"small"}
fxa-profile-server.compute.image-cc.VERBOSE: gm.limit {"disk":"2MB","files":"8","map":"2MB","memory":"1MB","pixels":"16K","threads":"8"}
fxa-profile-server.compute.image-cc.ERROR: compute Error: Stream yields empty buffer
    at Socket.<anonymous> (/data/fxa-profile-server/node_modules/gm/lib/command.js:65:17)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
fxa-profile-server.compute.DEBUG: image-cc process 19026 completed work in 1.54s
fxa-profile-server.compute.image-cc.INFO: worker.config {"config":{"driver":"local","providers":{"gravatar":"^http(://www|s://secure)\\.gravatar\\.com/avatar/[0-9a-f]{32}(\\?s=\\d+)?$","fxa":"^https://latest.dev.lcip.org/profile/a/[0-9a-f]{32}$"},"uploads":{"dest":{"public":"/data/fxa-profile-server/var/public"},"maxSize":1048576},"compute":{"maxBacklog":500,"maxRequestTime":10,"maxProcesses":5},"gm":{"limits":{"disk":"2MB","files":"8","map":"2MB","memory":"1MB","pixels":"16K","threads":"8"}},"url":"https://latest.dev.lcip.org/profile/a/{id}"}}
fxa-profile-server.compute.image-cc.DEBUG: onMessage 3649226ad8bf6b4e898a9cf97c62ca3a
fxa-profile-server.compute.image-cc.DEBUG: process.start {"bytes":55305,"variant":"large"}
fxa-profile-server.compute.image-cc.VERBOSE: gm.limit {"disk":"2MB","files":"8","map":"2MB","memory":"1MB","pixels":"16K","threads":"8"}
fxa-profile-server.compute.image-cc.INFO: worker.config {"config":{"driver":"local","providers":{"gravatar":"^http(://www|s://secure)\\.gravatar\\.com/avatar/[0-9a-f]{32}(\\?s=\\d+)?$","fxa":"^https://latest.dev.lcip.org/profile/a/[0-9a-f]{32}$"},"uploads":{"dest":{"public":"/data/fxa-profile-server/var/public"},"maxSize":1048576},"compute":{"maxBacklog":500,"maxRequestTime":10,"maxProcesses":5},"gm":{"limits":{"disk":"2MB","files":"8","map":"2MB","memory":"1MB","pixels":"16K","threads":"8"}},"url":"https://latest.dev.lcip.org/profile/a/{id}"}}
fxa-profile-server.compute.image-cc.DEBUG: onMessage 3649226ad8bf6b4e898a9cf97c62ca3a
fxa-profile-server.compute.image-cc.DEBUG: process.start {"bytes":55305,"variant":"default"}
fxa-profile-server.compute.image-cc.VERBOSE: gm.limit {"disk":"2MB","files":"8","map":"2MB","memory":"1MB","pixels":"16K","threads":"8"}
fxa-profile-server.compute.image-cc.INFO: time.ms.gm.large 865
fxa-profile-server.compute.image-cc.DEBUG: process.end {"bytes":454433,"variant":"large"}
fxa-profile-server.img.DEBUG: connected local
fxa-profile-server.img.VERBOSE: proxied {"method":"upload","args":3}
fxa-profile-server.img.local.DEBUG: upload.start 3649226ad8bf6b4e898a9cf97c62ca3a_large
fxa-profile-server.img.local.DEBUG: upload.end 3649226ad8bf6b4e898a9cf97c62ca3a_large
fxa-profile-server.compute.image-cc.INFO: time.ms.s3.large 16
fxa-profile-server.compute.DEBUG: image-cc process 19030 completed work in 2.21s
fxa-profile-server.compute.image-cc.INFO: time.ms.gm.default 886
fxa-profile-server.compute.image-cc.DEBUG: process.end {"bytes":454433,"variant":"default"}
fxa-profile-server.img.DEBUG: connected local
fxa-profile-server.img.VERBOSE: proxied {"method":"upload","args":3}
fxa-profile-server.img.local.DEBUG: upload.start 3649226ad8bf6b4e898a9cf97c62ca3a
fxa-profile-server.img.local.DEBUG: upload.end 3649226ad8bf6b4e898a9cf97c62ca3a
fxa-profile-server.compute.image-cc.INFO: time.ms.s3.default 13
fxa-profile-server.compute.DEBUG: image-cc process 19028 completed work in 2.38s
```

**Comment by vladikoff** [comment]
This diff fixed it for me on latest:
```diff
diff --git a/lib/config.js b/lib/config.js
index 13c9d30..88e1b5b 100644
--- a/lib/config.js
+++ b/lib/config.js
@@ -91,10 +91,10 @@ const conf = convict({
     gm: {
       limits: {
         // See http://www.graphicsmagick.org/GraphicsMagick.html#details-limit
-        disk: '2MB',
+        disk: '64MB',
         files: '8',
-        map: '2MB',
-        memory: '1MB',
+        map: '32MB',
+        memory: '64MB',
         pixels: '16K',
         threads: '8'
       }
```
