### ISSUE TITLE
prod errors train-50

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#176]
Example: 

```
{"Timestamp":1448489854219000000,"Logger":"fxa-profile-server","Type":"routes.email.request.auth_server.fail","Severity":2,"Pid":2054,"EnvVersion":"2.0","Fields":{"code":400}}
{"Timestamp":1448489854221000000,"Logger":"fxa-profile-server","Type":"server.summary","Severity":2,"Pid":2054,"EnvVersion":"2.0","Fields":{"code":503,"method":"get","errno":105,"path":"/v1/email","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:42.0) Gecko/20100101 Firefox/42.0","t":27,"stack":"Error: Auth server error
    at new authError (/data/fxa-profile-server/lib/error.js:142:10)
    at Request._callback (/data/fxa-profile-server/lib/routes/email.js:37:22)
    at Request.self.callback (/data/fxa-profile-server/node_modules/request/request.js:372:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/data/fxa-profile-server/node_modules/request/request.js:1310:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/data/fxa-profile-server/node_modules/request/request.js:1258:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:492:13)"}}
{"Timestamp":1448489854223000000,"Logger":"fxa-profile-server","Type":"batch.email.503","Severity":2,"Pid":2054,"EnvVersion":"2.0","Fields":{"code":503,"errno":105,"error":"Service Unavailable","message":"Auth server error","cause":"auth server error"}}
{"Timestamp":1448489854224000000,"Logger":"fxa-profile-server","Type":"server.summary","Severity":2,"Pid":2054,"EnvVersion":"2.0","Fields":{"code":503,"method":"get","errno":105,"path":"/v1/profile","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:42.0) Gecko/20100101 Firefox/42.0","t":86,"stack":"Error: Auth server error
    at Function.from (/data/fxa-profile-server/lib/error.js:51:13)
    at /data/fxa-profile-server/lib/batch.js:47:26
    at tryCatch1 (/data/fxa-profile-server/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/data/fxa-profile-server/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/data/fxa-profile-server/node_modules/bluebird/js/main/promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/data/fxa-profile-server/node_modules/bluebird/js/main/promise.js:845:14)
    at Promise$_settlePromises [as _settlePromises] (/data/fxa-profile-server/node_modules/bluebird/js/main/promise.js:988:14)
    at Promise.b (domain.js:183:18)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/data/fxa-profile-server/node_modules/bluebird/js/main/async.js:77:12)
    at Async$consumeFunctionBuffer (/data/fxa-profile-server/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickDomainCallback (node.js:492:13)"}}
```

**Comment by rfk** [comment]
> oauth traffic requests doubled during this period

IIUC this is expected, @seanmonstar should be able to confirm

**Comment by rfk** [comment]
> {"Timestamp":1448489854219000000,"Logger":"fxa-profile-server","Type":"routes.email.request.auth_server.fail","Severity":2,"Pid":2054,"EnvVersion":"2.0","Fields":{"code":400}}

It'd be handy to know what the application errno was that accompanied this 400 error; any chance we can find them in the auth-server's logs?

**Comment by jrgm** [comment]
Yeah, https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#dashboard/temp/AVFA8R4uayLd6KaGV4N0

Responses are all 400/102 on /account/profile.

**Comment by rfk** [comment]
```
status code 400, errno 102:  attempt to access an account that does not exist
```

Ugh.  So, these are accounts that have been deleted on the auth-sever, but which still have clients out in the wild trying to use oauth tokens for them?  How strange.

**Comment by rfk** [comment]
I *guess* this could be caused by folks entering an invalid email in the sync setup flow.  The account gets created, the browser goes to fetch profile data, but the account is quickly deleted again thanks to our bounced-email processing.

**Comment by jrgm** [comment]
Btw, this 400/102 response is on the order of 3 in 10000 queries to /account/profile

**Comment by rfk** [comment]
Typo-ed emails could probably explain it all at that low volume.

**Comment by rfk** [comment]
@jrgm to sanity-check, is the SQS link between auth->oauth currently set up, so that oauth can process account deletions in production?

**Comment by jrgm** [comment]
Yes, it is talking to the queue and reporting account deletions like so:
{"Timestamp":1448480251689000000,"Logger":"fxa-oauth-server",
 "Type":"events.delete","Severity":6,"Pid":2067,
 "EnvVersion":"2.0","Fields":{"uid":"cff1...d41b"}}
