### ISSUE TITLE
Avoid printing error tracebacks on the log for successful test runs

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#203]
Noticed in the travis logs that this error is thrown in (I think) `should error our on unexpected 400s from auth server`. (But running tests individually doesn't appear to produce the error). 

```
fxa-profile-server.server.ERROR: summary {"code":500,"method":"get","errno":999,"path":"/v1/email",
  "agent":"shot","t":227377,"stack":"Error: error communicating with auth server
    at Request.module.exports.handler [as _callback] (/Users/jrgm/tmp33/fxa-profile-server/lib/routes/email.js:54:22)
    at Request.init.self.callback (/Users/jrgm/tmp33/fxa-profile-server/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.readResponseBody (/Users/jrgm/tmp33/fxa-profile-server/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.Request.onRequestResponse (/Users/jrgm/tmp33/fxa-profile-server/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)"}
```

**Comment by seanmonstar** [comment]
The test checks for several logs, and for the 500 status code: https://github.com/mozilla/fxa-profile-server/blob/master/test/api.js#L200

Working as intended. We could probably add a mock for the log to not output that summary of a 500, since it looks misleading in the output.
