### ISSUE TITLE
running npm test -> possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#262]
Happened to notice this running tests locally, and visible here https://travis-ci.org/mozilla/fxa-profile-server/jobs/248158970#L1262 when running under travis. 
```
(node) warning: possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at Array.forEach (native)
    at unmanageExceptions (/home/travis/build/mozilla/fxa-profile-server/node_modules/grunt-mocha-test/tasks/mocha-test.js:74:33)
    at restore (/home/travis/build/mozilla/fxa-profile-server/node_modules/grunt-mocha-test/tasks/mocha-test.js:78:7)
    at /home/travis/build/mozilla/fxa-profile-server/node_modules/grunt-mocha-test/tasks/mocha-test.js:97:7
    at /home/travis/build/mozilla/fxa-profile-server/node_modules/grunt-mocha-test/tasks/mocha-test.js:41:7
    at /home/travis/build/mozilla/fxa-profile-server/node_modules/grunt-mocha-test/tasks/mocha-test.js:92:11
    at /home/travis/build/mozilla/fxa-profile-server/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:81:13
    at Runner.<anonymous> (/home/travis/build/mozilla/fxa-profile-server/node_modules/mocha/lib/runner.js:825:5)
    at emitNone (events.js:72:20)
    at Runner.emit (events.js:166:7)
    at /home/travis/build/mozilla/fxa-profile-server/node_modules/mocha/lib/runner.js:812:12
    at /home/travis/build/mozilla/fxa-profile-server/node_modules/mocha/lib/runner.js:660:9
    at next (/home/travis/build/mozilla/fxa-profile-server/node_modules/mocha/lib/runner.js:295:14)
    at /home/travis/build/mozilla/fxa-profile-server/node_modules/mocha/lib/runner.js:334:7
    at done (/home/travis/build/mozilla/fxa-profile-server/node_modules/mocha/lib/runnable.js:295:5)
    at /home/travis/build/mozilla/fxa-profile-server/node_modules/mocha/lib/runnable.js:353:11
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/home/travis/build/mozilla/fxa-profile-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/mozilla/fxa-profile-server/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/travis/build/mozilla/fxa-profile-server/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/travis/build/mozilla/fxa-profile-server/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/travis/build/mozilla/fxa-profile-server/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/travis/build/mozilla/fxa-profile-server/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/travis/build/mozilla/fxa-profile-server/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/mozilla/fxa-profile-server/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

**Comment by vladikoff** [comment]
Possible fix: https://github.com/mozilla/fxa-auth-server/commit/dae0e5834086f92399ac16336cd8d42bd524388c

**Comment by hritvi** [comment]
Hey @vladikoff! Can I work on this issue? Thanks :)

**Comment by vladikoff** [comment]
@hritvi sure! see this solution from the other repository, it might work here: https://github.com/mozilla/fxa-auth-server/commit/dae0e5834086f92399ac16336cd8d42bd524388c

**Comment by hritvi** [comment]
Hey, @vladikoff! Do I have to add the fix in [test/events.js](https://github.com/mozilla/fxa-profile-server/blob/master/test/events.js)? Thanks

**Comment by hritvi** [comment]
@vladikoff Any updates on this bug? Thanks :)

**Comment by vladikoff** [comment]
@hritvi hey, I didn't dive into this bug, you can determine which test file to fix if you run the test and start excluding the test files for each run. this you can find which tests are causing the leak

**Comment by deeptibaghel** [comment]
@vladikoff these warnings are not showing any more, like here https://travis-ci.org/mozilla/fxa-profile-server/jobs/360606284
Does it occur in some specific case only ?

**Comment by vladikoff** [comment]
@deeptibaghel Hey, I don't see those anymore, but I see 

```
  profile cache
fxa-profile-server.updates_queue.ERROR: SQSSender.send No SQS region or queueURL provided, SQS features will be disabled
(node:20028) DeprecationWarning: mozlog.config() is deprecated. Use mozlog(opts) to receive a specific mozlog instance.
    ✓ should cache profile info initially, and invalidate cache after 2 seconds (2056ms)
fxa-profile-server.updates_queue.ERROR: SQSSender.send No SQS region or queueURL provided, SQS features will be disabled
(node:20028) DeprecationWarning: mozlog.config() is deprecated. Use mozlog(opts) to receive a specific mozlog instance.
    ✓ should not cache for non qa emails (1030ms)
fxa-profile-server.updates_queue.ERROR: SQSSender.send No SQS region or queueURL provided, SQS features will be disabled
(node:20028) DeprecationWarning: mozlog.config() is deprecated. Use mozlog(opts) to receive a specific mozlog instance.
    ✓ should invalidate cache when display name is updated (1041ms)
fxa-profile-server.updates_queue.ERROR: SQSSender.send No SQS region or queueURL provided, SQS features will be disabled
(node:20028) DeprecationWarning: mozlog.config() is deprecated. Use mozlog(opts) to receive a specific mozlog instance.
    ✓ should invalidate cache when avatar is updated (1151ms)
```

I wonder if we can fix those `DeprecationWarning` up

**Comment by deeptibaghel** [comment]
@vladikoff ok i will fix the deprecation warnings.

**Comment by vladikoff** [comment]
this was fixed 👍
